/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FileIntegrityInterface extends Interface {
    getFunction(nameOrSignature: "registerFile" | "verifyFile"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FileRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'registerFile', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'verifyFile', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'registerFile', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyFile', data: BytesLike): Result;
  }

  
    export namespace FileRegisteredEvent {
      export type InputTuple = [fileHash: BytesLike, uploader: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [fileHash: string, uploader: string, timestamp: bigint];
      export interface OutputObject {fileHash: string, uploader: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FileIntegrity extends BaseContract {
    
    connect(runner?: ContractRunner | null): FileIntegrity;
    waitForDeployment(): Promise<this>;

    interface: FileIntegrityInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    registerFile: TypedContractMethod<
      [fileHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifyFile: TypedContractMethod<
      [fileHash: BytesLike, ],
      [[boolean, string, bigint] & {exists: boolean, uploader: string, timestamp: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'registerFile'): TypedContractMethod<
      [fileHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyFile'): TypedContractMethod<
      [fileHash: BytesLike, ],
      [[boolean, string, bigint] & {exists: boolean, uploader: string, timestamp: bigint }],
      'view'
    >;

    getEvent(key: 'FileRegistered'): TypedContractEvent<FileRegisteredEvent.InputTuple, FileRegisteredEvent.OutputTuple, FileRegisteredEvent.OutputObject>;

    filters: {
      
      'FileRegistered(bytes32,address,uint256)': TypedContractEvent<FileRegisteredEvent.InputTuple, FileRegisteredEvent.OutputTuple, FileRegisteredEvent.OutputObject>;
      FileRegistered: TypedContractEvent<FileRegisteredEvent.InputTuple, FileRegisteredEvent.OutputTuple, FileRegisteredEvent.OutputObject>;
    
    };
  }